// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefundWebApplication.Data;

#nullable disable

namespace RefundWebApplication.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20240115180123_Seed2")]
    partial class Seed2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RefundWebApplication.Models.Domain.AttachmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComplaintModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintModelId");

                    b.ToTable("AttachmentModel");
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.ComplaintHistoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComplaintModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintModelId");

                    b.ToTable("ComplaintHistoryModel");
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.ComplaintModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComplaintModel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f117825f-f03c-413f-a51a-efcc90f0af4f"),
                            City = "Sample Town",
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            HouseNumber = "Suite 101",
                            IssueDescription = "Product issue description goes here",
                            LastName = "Smith",
                            Phone = "555-987-6543",
                            PostalCode = "54321",
                            PurchaseDate = new DateTime(2023, 10, 15, 19, 1, 23, 287, DateTimeKind.Local).AddTicks(2546),
                            SerialNumber = "0987654321",
                            Street = "456 Oak St"
                        });
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.CustomerModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ComplaintModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintModelId");

                    b.ToTable("CustomerModel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72d4869c-5304-450e-be87-c806162ffca0"),
                            City = "Example City",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            HouseNumber = "Apt 4B",
                            LastName = "Doe",
                            Phone = "555-555-5555",
                            PostalCode = "12345",
                            Street = "123 Main Street"
                        });
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.EmailLogsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComplaintModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintModelId");

                    b.ToTable("EmailLogsModel");
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.ProductModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComplaintModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WarrantyEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintModelId");

                    b.ToTable("ProductModel");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f0c8b2f-59a8-4358-9076-b4f252cab91d"),
                            Name = "Example Product",
                            PurchaseDate = new DateTime(2023, 10, 15, 19, 1, 23, 281, DateTimeKind.Local).AddTicks(8961),
                            SerialNumber = "1234567890",
                            WarrantyEndDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.AttachmentModel", b =>
                {
                    b.HasOne("RefundWebApplication.Models.Domain.ComplaintModel", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ComplaintModelId");
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.ComplaintHistoryModel", b =>
                {
                    b.HasOne("RefundWebApplication.Models.Domain.ComplaintModel", null)
                        .WithMany("History")
                        .HasForeignKey("ComplaintModelId");
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.CustomerModel", b =>
                {
                    b.HasOne("RefundWebApplication.Models.Domain.ComplaintModel", null)
                        .WithMany("Customer")
                        .HasForeignKey("ComplaintModelId");
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.EmailLogsModel", b =>
                {
                    b.HasOne("RefundWebApplication.Models.Domain.ComplaintModel", null)
                        .WithMany("EmailLogs")
                        .HasForeignKey("ComplaintModelId");
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.ProductModel", b =>
                {
                    b.HasOne("RefundWebApplication.Models.Domain.ComplaintModel", null)
                        .WithMany("Products")
                        .HasForeignKey("ComplaintModelId");
                });

            modelBuilder.Entity("RefundWebApplication.Models.Domain.ComplaintModel", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Customer");

                    b.Navigation("EmailLogs");

                    b.Navigation("History");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
